version: "3"
services:
  server:          
      build:
        dockerfile: Dockerfile
        context: ./
      container_name: docker_server
      restart: unless-stopped
      ports:
        - "8090:8090"
      volumes: 
          - ./:/app
          - /app/node_modules/
          - /app/node_modules/bcrypt/
