version: "3"
services:
  server:          
      build:
        dockerfile: Dockerfile
        context: ./
      container_name: docker_server
      restart: unless-stopped
      ports:
        - "8080:8080"
      volumes: 
          - ./:/app
          - /app/node_modules/
          - /app/node_modules/bcrypt/

# 도커 컨테이너 실행 시
# package.json / script: "start": "NODE_ENV=production nodemon app.js " 수정
# docker-compose up 명령어 입력
